import type {LucideIcon} from "lucide-react";
import type {CardGridItem} from "@/components/sections/card-grid";
import type {FaqItem} from "@/components/sections/faq-accordion";
import type {HeroFeatured} from "@/components/sections/hero";
import type {ProcessStep} from "@/components/sections/how-it-works";
import type {IntegrationItem} from "@/components/sections/integrations";
import type {PricingPlan} from "@/components/sections/pricing-table";
import type {TestimonialItem} from "@/components/sections/testimonials";

export type ProductLandingContent = {
  slug: string;
  name: string;
  category: string;
  eyebrow: string;
  title: string;
  description: string;
  seoTitle: string;
  seoDescription: string;
  primaryCta: {href: string; label: string};
  secondaryCta: {href: string; label: string};
  featured: HeroFeatured;
  proof: string[];
  featuresEyebrow: string;
  featuresTitle: string;
  featuresDescription: string;
  features: CardGridItem[];
  processEyebrow: string;
  processTitle: string;
  processDescription?: string;
  steps: ProcessStep[];
  stackEyebrow: string;
  stackTitle: string;
  integrations: IntegrationItem[];
  pricingEyebrow: string;
  pricingTitle: string;
  pricingDescription: string;
  plans: PricingPlan[];
  reviewsEyebrow: string;
  reviewsTitle: string;
  testimonials: TestimonialItem[];
  faqEyebrow: string;
  faqTitle: string;
  faqs: FaqItem[];
  ctaTitle: string;
  ctaDescription: string;
  ctaLabel: string;
  icon?: LucideIcon;
};
